version: "2.1"

services:
  cyberway-notifier:
    container_name: cyberway.event-engine-reader
    image: cyberway/cyberway.event-engine-reader:local
    restart: always
    command: bash -c "exec /opt/cyberway/bin/cyberway.event-engine-reader"
    volumes:
      - cyberway-queue:/queue:ro

  mongo:
    container_name: mongo
    image: mongo:4.0.6-xenial
    restart: always
    healthcheck:
       test: mongo --eval 'db.getCollectionNames()'
       interval: 10s
       timeout: 2s
       retries: 10
    volumes:
      - cyberway-mongodb-data:/data/db
    ports:
      - 127.0.0.1:27018:27017
    networks:
      - cyberway-net

  nodeosd:
    container_name: nodeosd
    image: cyberway/cyberway:latest
    depends_on:
      mongo:
        condition: service_healthy
    command: bash -c "exec /opt/cyberway/bin/nodeosd.sh --data-dir /opt/cyberway/bin/data-dir -e --http-alias=nodeosd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888 --plugin eosio::event_engine_plugin --event-engine-unix-socket /queue/msg.sock --genesis-json /opt/cyberway/bin/genesis-data/genesis.json --genesis-data /opt/cyberway/bin/genesis-data/genesis.dat ${EXTRA_NODEOS_ARGS}"
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - cyberway-nodeos-data:/opt/cyberway/bin/data-dir
      - ${PWD}/config.ini:/opt/cyberway/bin/data-dir/config.ini
      - ${PWD}/genesis-data:/opt/cyberway/bin/genesis-data
      - cyberway-queue:/queue
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m
    networks:
      - cyberway-net

volumes:
 cyberway-mongodb-data:
   external: true
 cyberway-nodeos-data:
   external: true
 cyberway-queue:
   external: true

networks:
  cyberway-net:
